### ISSUE TITLE
What does this plugin do and how do I use it?

### ISSUE THREAD

**Issue by wilsonpage** [delianides/kap-vercel#3]
I'm a Vercel user and was curious what this plugin did. The readme just tell me how to install. I installed it and now I don't see anything in the UI about how to use it.

**Comment by AlecRust** [comment]
As mentioned on the [usage section](https://github.com/delianides/kap-vercel#usage) of the readme:

> In the editor, after recording, select one of the export formats, and then Share on Vercel.

![image](https://user-images.githubusercontent.com/247634/127308870-082e8023-15a4-4f52-93a4-7b0cd6cbc7d1.png)

That is the intended behaviour. Whether it works fully after the Now -> Vercel rename and whether it has kept up to date with Vercel changes, is another story. kap-now has worked for me in the past, kap-vercel has never really worked for me.

**Comment by delianides** [comment]
@AlecRust what doesn't work for you?

**Comment by AlecRust** [comment]
@delianides I think I was confused with `kap-now` the previous version of this plugin, which seemed to still partially be installed. All ok now 👍

**Comment by danielo515** [comment]
But what is it supposed to do? Vercel is a platform to deploy websites so...

**Comment by AlecRust** [comment]
It creates a Vercel website instance, that contains the MP4.

**Comment by danielo515** [comment]
OK, that answers the question. thanks
